version = 1

[[analyzers]]
name = "swift"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"